# Generated by Django 5.1.1 on 2024-10-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"permissions": []},
        ),
        migrations.AddField(
            model_name="post",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남"), ("F", "여"), ("O", "기타")],
                max_length=1,
                null=True,
            ),
        ),
    ]
